services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppassword
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./app
    environment:
      DATABASE_URL: postgresql://appuser:apppassword@db:5432/appdb
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./app:/app

volumes:
  postgres_data:
